algoritmo "cadastro"
var

nome, sobrenome, conjugue, endereco, estado, telefone: caractere

inicio

  // saida de dados
  escreva ("digite um nome:")
  
  // entrada de dados
  leia (nome)

  escreva("digite sobrenome:")
  leia (sobrenome)
  
  escreva("digite conjugue:")
  leia (conjugue)
  
  escreva("digite telefone:")
  leia (telefone)
  
  escreva ("digite endereco:")
  leia (endereco)
  
  escreva("digite Estado:")
  leia (estado)

fimalgoritmo